jwt:
  secret: mysecretkey1234567890
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: appointment-service
          uri: http://localhost:8082
          predicates:
            - Path=/appointments/**
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**

server:
  port: 8080
